

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82"],
		"CDFG" : "cnn_accelerator",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "17955", "EstimateLatencyMax" : "17955",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "IO",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270", "Port" : "gmem", "Inst_start_state" : "77", "Inst_end_state" : "78"}]},
			{"Name" : "input_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "weights8", "Type" : "None", "Direction" : "I"},
			{"Name" : "weights6", "Type" : "None", "Direction" : "I"},
			{"Name" : "weights4", "Type" : "None", "Direction" : "I"},
			{"Name" : "weights2", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "Cin", "Type" : "None", "Direction" : "I"},
			{"Name" : "Cout", "Type" : "None", "Direction" : "I"},
			{"Name" : "H", "Type" : "None", "Direction" : "I"},
			{"Name" : "W", "Type" : "None", "Direction" : "I"},
			{"Name" : "precision", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_39_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "78", "FirstState" : "ap_ST_fsm_state4", "LastState" : ["ap_ST_fsm_state78"], "QuitState" : ["ap_ST_fsm_state4"], "PreState" : ["ap_ST_fsm_state3"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270", "Parent" : "0", "Child" : ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67"],
		"CDFG" : "cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1047", "EstimateLatencyMax" : "1047",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "IO",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_B", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_AW", "Type" : "RtlSignal"}]},
			{"Name" : "precision", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln39", "Type" : "None", "Direction" : "I"},
			{"Name" : "phi_mul7", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_30", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_31", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_32", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_33", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_15_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_34", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_35", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_16_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_36", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_37", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_17_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_38", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_39", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_18_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_40", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_41", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_19_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_42", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_43", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_20_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_44", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_45", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_21_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_22_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_46", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_47", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_48", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_49", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_23_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_50", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_51", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_24_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_52", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_53", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_25_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_54", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_55", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_26_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_56", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_57", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_27_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_58", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_59", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_28_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_60", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "bh_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "w8_29_cast", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_40_2_VITIS_LOOP_41_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "16", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage5", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage5_subdone", "QuitState" : "ap_ST_fsm_pp0_stage5", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage5_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4ns_32s_36_2_1_U1", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U2", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U3", "Parent" : "1"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U4", "Parent" : "1"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U5", "Parent" : "1"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U6", "Parent" : "1"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U7", "Parent" : "1"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U8", "Parent" : "1"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U9", "Parent" : "1"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U10", "Parent" : "1"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U11", "Parent" : "1"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U12", "Parent" : "1"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U13", "Parent" : "1"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U14", "Parent" : "1"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U15", "Parent" : "1"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U16", "Parent" : "1"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U17", "Parent" : "1"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U18", "Parent" : "1"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U19", "Parent" : "1"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U20", "Parent" : "1"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U21", "Parent" : "1"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U22", "Parent" : "1"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U23", "Parent" : "1"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U24", "Parent" : "1"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U25", "Parent" : "1"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U26", "Parent" : "1"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U27", "Parent" : "1"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U28", "Parent" : "1"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U29", "Parent" : "1"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U30", "Parent" : "1"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U31", "Parent" : "1"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U32", "Parent" : "1"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U33", "Parent" : "1"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U34", "Parent" : "1"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U35", "Parent" : "1"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U36", "Parent" : "1"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U37", "Parent" : "1"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U38", "Parent" : "1"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U39", "Parent" : "1"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U40", "Parent" : "1"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U41", "Parent" : "1"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U42", "Parent" : "1"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U43", "Parent" : "1"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U44", "Parent" : "1"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U45", "Parent" : "1"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U46", "Parent" : "1"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U47", "Parent" : "1"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U48", "Parent" : "1"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U49", "Parent" : "1"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U50", "Parent" : "1"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U51", "Parent" : "1"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U52", "Parent" : "1"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U53", "Parent" : "1"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U54", "Parent" : "1"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U55", "Parent" : "1"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U56", "Parent" : "1"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U57", "Parent" : "1"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U58", "Parent" : "1"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U59", "Parent" : "1"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U60", "Parent" : "1"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U61", "Parent" : "1"},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_2s_2s_2_1_1_U62", "Parent" : "1"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U63", "Parent" : "1"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_4s_4s_4_1_1_U64", "Parent" : "1"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.mul_8s_8s_16_1_1_U65", "Parent" : "1"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accelerator_Pipeline_VITIS_LOOP_40_2_VITIS_LOOP_41_3_fu_270.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"},
	{"ID" : "68", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "69", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_m_axi_U", "Parent" : "0"},
	{"ID" : "70", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U155", "Parent" : "0"},
	{"ID" : "71", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U156", "Parent" : "0"},
	{"ID" : "72", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U157", "Parent" : "0"},
	{"ID" : "73", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U158", "Parent" : "0"},
	{"ID" : "74", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U159", "Parent" : "0"},
	{"ID" : "75", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U160", "Parent" : "0"},
	{"ID" : "76", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U161", "Parent" : "0"},
	{"ID" : "77", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U162", "Parent" : "0"},
	{"ID" : "78", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U163", "Parent" : "0"},
	{"ID" : "79", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U164", "Parent" : "0"},
	{"ID" : "80", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U165", "Parent" : "0"},
	{"ID" : "81", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_2_1_U166", "Parent" : "0"},
	{"ID" : "82", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_62_2_1_U167", "Parent" : "0"}]}
