domain_path: C:\Users\ishan\ECT_110_vitis\cordicbeta\export\cordicbeta\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
