# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/cnn_controler/cnn_controler.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_controler || ORIG_REF_NAME==cnn_controler} -quiet] -quiet

# IP: bd/cnn_controler/ip/cnn_controler_processing_system7_0_0/cnn_controler_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_controler_processing_system7_0_0 || ORIG_REF_NAME==cnn_controler_processing_system7_0_0} -quiet] -quiet

# IP: bd/cnn_controler/ip/cnn_controler_cnn_accelerator_0_0/cnn_controler_cnn_accelerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_controler_cnn_accelerator_0_0 || ORIG_REF_NAME==cnn_controler_cnn_accelerator_0_0} -quiet] -quiet

# IP: bd/cnn_controler/ip/cnn_controler_axi_smc_0/cnn_controler_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_controler_axi_smc_0 || ORIG_REF_NAME==cnn_controler_axi_smc_0} -quiet] -quiet

# Block Designs: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/bd_dee4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_0/bd_dee4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_1/bd_dee4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_2/bd_dee4_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_3/bd_dee4_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_4/bd_dee4_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_5/bd_dee4_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_6/bd_dee4_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_7/bd_dee4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_8/bd_dee4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_9/bd_dee4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_10/bd_dee4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_11/bd_dee4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_12/bd_dee4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_13/bd_dee4_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_14/bd_dee4_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_15/bd_dee4_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_16/bd_dee4_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_17/bd_dee4_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_18/bd_dee4_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_19/bd_dee4_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_20/bd_dee4_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_21/bd_dee4_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_22/bd_dee4_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_23/bd_dee4_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_24/bd_dee4_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_25/bd_dee4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_26/bd_dee4_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_27/bd_dee4_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_28/bd_dee4_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_29/bd_dee4_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_30/bd_dee4_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_31/bd_dee4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_32/bd_dee4_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_33/bd_dee4_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_34/bd_dee4_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_35/bd_dee4_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_36/bd_dee4_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_37/bd_dee4_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_38/bd_dee4_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_39/bd_dee4_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_40/bd_dee4_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_41/bd_dee4_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_42/bd_dee4_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_43/bd_dee4_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_44/bd_dee4_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_45/bd_dee4_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/cnn_controler/ip/cnn_controler_rst_ps7_0_100M_0/cnn_controler_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_controler_rst_ps7_0_100M_0 || ORIG_REF_NAME==cnn_controler_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/cnn_controler/ip/cnn_controler_axi_gpio_0_0/cnn_controler_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_controler_axi_gpio_0_0 || ORIG_REF_NAME==cnn_controler_axi_gpio_0_0} -quiet] -quiet

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_processing_system7_0_0/cnn_controler_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cnn_controler_processing_system7_0_0 || ORIG_REF_NAME==cnn_controler_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_cnn_accelerator_0_0/constraints/cnn_accelerator_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_1/bd_dee4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_2/bd_dee4_arsw_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_3/bd_dee4_rsw_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_4/bd_dee4_awsw_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_5/bd_dee4_wsw_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_6/bd_dee4_bsw_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_10/bd_dee4_s00a2s_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_11/bd_dee4_sarn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_12/bd_dee4_srn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_13/bd_dee4_sawn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_14/bd_dee4_swn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_15/bd_dee4_sbn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_19/bd_dee4_s01a2s_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_20/bd_dee4_sarn_1_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_21/bd_dee4_srn_1_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_22/bd_dee4_sawn_1_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_23/bd_dee4_swn_1_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_24/bd_dee4_sbn_1_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_25/bd_dee4_m00s2a_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_26/bd_dee4_m00arn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_27/bd_dee4_m00rn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_28/bd_dee4_m00awn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_29/bd_dee4_m00wn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_30/bd_dee4_m00bn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_32/bd_dee4_m01s2a_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_33/bd_dee4_m01arn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_34/bd_dee4_m01rn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_35/bd_dee4_m01awn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_36/bd_dee4_m01wn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_37/bd_dee4_m01bn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_39/bd_dee4_m02s2a_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_40/bd_dee4_m02arn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_41/bd_dee4_m02rn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_42/bd_dee4_m02awn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_43/bd_dee4_m02wn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/bd_0/ip/ip_44/bd_dee4_m02bn_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cnn_controler_axi_smc_0 || ORIG_REF_NAME==cnn_controler_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_rst_ps7_0_100M_0/cnn_controler_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cnn_controler_rst_ps7_0_100M_0 || ORIG_REF_NAME==cnn_controler_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_gpio_0_0/cnn_controler_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cnn_controler_axi_gpio_0_0 || ORIG_REF_NAME==cnn_controler_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/ip/cnn_controler_axi_gpio_0_0/cnn_controler_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/ishan/ECT110/project_7/project_7.gen/sources_1/bd/cnn_controler/cnn_controler_ooc.xdc
